version: "3.9"

x-config: &config
  ulimits:
    memlock:
      soft: -1
      hard: -1
    nofile:
      soft: 65536
      hard: 65536

services:
  ddb_controller2:
    <<: *config
    image: ${IMAGE}
    container_name: ddb_controller2
    volumes:
      - ./dolphindb.lic:${CON_LIC}
      - ${HOST_CFG}/controller2.cfg:${CON_FIG}/controller2.cfg
      - ${HOST_CFG}/cluster.cfg:${CON_FIG}/cluster.cfg
      - ${HOST_CFG}/cluster.nodes:${CON_FIG}/cluster.nodes
      - ${HOST_CON_DATA}:${CON_DATA}
      - ${HOST_CON_LOG}:${CON_LOG}
    entrypoint: ["sh", "-c", "cd /data/ddb/server;./dolphindb -console 0 -mode controller -home clusterDemo/data -script dolphindb.dos -config clusterDemo/config/controller2.cfg -logFile clusterDemo/log/controller2.log -nodesFile clusterDemo/config/cluster.nodes -clusterConfig clusterDemo/config/cluster.cfg"]

    restart: always
    

    ports:
      - "8902:8902"

    networks:
      dev_dolphindb:
        ipv4_address: 10.5.0.2
  
  ddb_agent2: 
    <<: *config
    image: ${IMAGE}
    container_name: ddb_agent2
    volumes:
      - ./dolphindb.lic:${CON_LIC}
      - ${HOST_CFG}/agent2.cfg:${CON_FIG}/agent2.cfg
      - ${HOST_AG_DATA}:${CON_DATA}
      - ${HOST_AG_LOG}:${CON_LOG}


    entrypoint: ["sh", "-c", "cd /data/ddb/server;./dolphindb -console 0 -mode agent -home clusterDemo/data -script dolphindb.dos -config clusterDemo/config/agent2.cfg -logFile clusterDemo/log/agent2.log"]
    
    restart: always

    depends_on:
      - ddb_controller2

    ports:
      - "8810:8810"
      - "8811:8811"

    
  
    networks:
      dev_dolphindb:
        ipv4_address: 10.5.0.6

networks:
  dev_dolphindb:
    name: dev_ddb
    driver: bridge
    ipam:
      config:
      - subnet: 10.5.0.0/16
